### ISSUE TITLE
Analyse Intel's WASM VM code

### ISSUE THREAD

**Issue by JoeyTeng** [deeplang-org/deeplang#3]
Add the analysis into [codereview.md](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/codereview.md)
- [x]  [rainc](https://github.com/orgs/deeplang-org/projects/1#column-10799367) @Rainc1116 
  - [x] [wasm_interp_classic.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_interp_classic.c)
  - [x] [wasm_native.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_native.c)
  - [x] [wasm_runtime_common.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_runtime_common.c)
  - [x] [invokeNative_general.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/invokeNative_general.c)
  - [x] [bh_common.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_common.c)
  - [x] [bh_queue.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_queue.c)
  - [x] [bh_list.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_list.c)
  - [x] [bh_read_file.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_read_file.c)
  - [x] [libc_builtin_wrapper.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/libc_builtin_wrapper.c)
- [ ] [Joey Teng](https://github.com/orgs/deeplang-org/projects/1#column-10799364) @JoeyTeng 
  - [x] [wasm_exec_env.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_exec_env.c)
  - [x] [wasm_memory.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_memory.c)
  - [x] [runtime_timer.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/runtime_timer.c)
  - [x] [bh_hashmap.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_hashmap.c)
  - [x] [ems_alloc.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/ems_alloc.c)
  - [x] [ems_kfc.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/ems_kfc.c)
  - [x] [mem_alloc.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/mem_alloc.c)
  - [ ] [posix_malloc.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/posix_malloc.c)
  - [ ] [posix_memmap.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/posix_memmap.c)
- [ ] [z123z123d](https://github.com/orgs/deeplang-org/projects/1#column-10799499) @z123z123d 
  - [x] [wasm_c_api.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_c_api.c)
  - [x] [wasm_loader.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_loader.c)
  - [ ] [wasm_runtime.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/wasm_runtime.c)
  - [x] [platform_init.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/platform_init.c)
  - [x] [bh_assert.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_assert.c)
  - [x] [bh_log.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_log.c)
  - [x] [bh_vector.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/bh_vector.c)
  - [x] [posix_thread.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/posix_thread.c)
  - [x] [posix_time.c](https://github.com/deeplang-org/deeplang/blob/wasmvm/src/vm/posix_time.c)

**Comment by chinesebear** [comment]
@z123z123d 看完后，按照格式填一下codereview.md

**Comment by chinesebear** [comment]
done
