### ISSUE TITLE
wasmvm compiling on win10 and linux

### ISSUE THREAD

**Issue by chinesebear** [deeplang-org/deeplang#7]
-  wasmvm compiling on win10 (MSYS2/GCC/MAKE)-------good
- wasmvm compiling on linux---------bad

**Comment by Rainc1116** [comment]
wasmvm now can compile successfully on Linux and Win10

**Comment by JoeyTeng** [comment]
Same issue occurs on Darwin (macOS) as well.

**Comment by JoeyTeng** [comment]
Seems that everything has been fixed by now. Please re-open this issue if anyone find any problems.
